server {
    listen 80;
    server_name _;

    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-XSS-Protection "1; mode=block";

    location /health {
        return 200 "OK\n";
    }

 # Version endpoint (PLACE IT HERE)
    location /version.json {
        try_files /version.json =404;
    }


    location /v1/templates.json {
        try_files /templates.json =404;
    }

    location /v2/templates.json {
        try_files /templates.json =404;
    }

    location /templates.json {
        try_files /templates.json =404;
    }

    location / {
        return 403;
    }
}
