version: "3.9"

services:
  template-server:
    image: tonesav/template-server:latest
    container_name: template-server
    restart: unless-stopped
    networks:
      - llm_net

networks:
  llm_net:
    external: true
