version: "3.9"

services:
  crew-agent:
    image: python:3.11
    container_name: crew-agent
    working_dir: /app
    restart: unless-stopped


    environment:
      OLLAMA_URL: "http://host.docker.internal:11434"
      MEILI_URL: "http://meilisearch:7700"
      MEILI_MASTER_KEY: "your_master_key_here"

    command: >
      sh -c "
      pip install crewai crewai-tools langchain-community requests &&
      python supervisor.py
      "

    networks:
      - llm_net

networks:
  llm_net:
    external: true

