version: "3.9"
services:
  rag-ingest-scheduled:
    image: tonesav/rag-ingest-scheduled:latest
    container_name: rag-ingest-scheduled
    restart: unless-stopped
    networks:
      - llm_net

networks:
  llm_net:
    external: true

